Added PR Check

diff --git a/.github/workflows/trigger_workflow_from_comment.yml b/.github/workflows/trigger_workflow_from_comment.yml
--- a/.github/workflows/trigger_workflow_from_comment.yml
+++ b/.github/workflows/trigger_workflow_from_comment.yml
@@ -15,7 +15,7 @@ jobs:
       checks: write
       contents: write
       pull-requests: read
-    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, vars.TRIGGER_COMMAND) }}
+    if: ${{ github.event.issue.pull_request }}
     runs-on: ubuntu-latest
     steps:
       - name: Get Workflow Details
@@ -24,6 +24,16 @@ jobs:
           input_str="${{ github.event.comment.body }}"
 
           # Remove the leading TRIGGER_COMMAND
+          input_trigger_command=${input_str%% *}
+
+          # Check if the command is correct
+          if [[ $input_trigger_command == $TRIGGER_COMMAND ]]; then
+              echo "The command is correct. Moving ahead."
+          else
+            echo "The command is not valid. Aborting."
+              exit 1
+          fi
+
           command_params=${input_str#$TRIGGER_COMMAND}
           IFS=' ' read -ra args <<< $command_params
 
